name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SufficientDaikon
          filename: metrics/metrics.svg
          config_timezone: Africa/Cairo
          config_padding: 6, 10
          config_output: svg
          base: header, repositories
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_categories: data, markup, programming
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          plugin_languages_colors: github
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_filter: stars:>1000
          plugin_notable_from: all
